### PR TITLE
Add delay

### PR DESCRIPTION
**Pull request by BenjaminVanRyseghem**
Add a short delay to avoid spamming inputs.
This comes from "Examples/Teensy/USB_Joystick/Complete".

### CODE REVIEW

**Comment by dmadison** [comment]
Thanks for the pull request, but this delay isn't needed - all USB IN (`send()`) calls block until the output is sent, so the loop is already limited to the max output rate.

**Comment by BenjaminVanRyseghem** [comment]
I trust you :smile: But when I tried with a Teensy 3.2, each button press was triggering 4/5 inputs, that's why I added the delay :smile:

Now you know, so I let you dispose of the PR as you wish :smile:

**Comment by dmadison** [comment]
If you're running into bounce issues them I'm sure the delay helped, but it also reduces the update rate by a little more than half. :grimacing: If you need a debounce it's better to use a hardware filter or the built-in Arduino timers (`millis()`, `micros()`) to do non-blocking software debounce.

**Comment by BenjaminVanRyseghem** [comment]
> If you need a debounce it's better to use a hardware filter or the built-in Arduino timers (millis(), micros()) to do non-blocking software debounce.

Could you tell me a bit more about this? I am a total noob when it comes to Arduino :smile:

**Comment by BenjaminVanRyseghem** [comment]
I am reading this about [debounce](https://www.arduino.cc/en/pmwiki.php?n=Tutorial/Debounce) but I am a bit worried about the `millis` "overflow" as stated [here](https://www.arduino.cc/reference/en/language/functions/time/micros/).

When `millis` loops back to 0, then an input might be skipped, or? (if `lastDebounceTime` happened before the loop, and the check after)

**Comment by dmadison** [comment]
>Could you tell me a bit more about this?

I'd recommend doing your own research, but the super short version is this:

* Hardware: Low pass (RC) filter
* Software: If T > debounce change the buffer and store T

In Arduino the latter looks like this:

```cpp
const unsigned long Debounce = 30;  // ms
unsigned long last = 0;
bool state = false;

{
  bool s = digitalRead(Pin);
  unsigned long t = millis();
  if(s != state && t - last >= Debounce) {
    state = s;
    last = t;
  }
}
```
Effectively, only record the change of the pin's state if 30 milliseconds have passed since the last recorded change. There are many, many libraries to simplify this for the user if you'd like.

>I am a bit worried about the millis "overflow" as stated here.

No reason to be, that's only an issue if you're working with timescales of that length (~70 minutes for microseconds, ~50 days for milliseconds). So long as you subtract the timestamp from `millis()` and work with relative times the binary math will ignore the overflow. You can test that yourself by trying the code above with a dummy function in place of `millis()` that returns a number at or close to the overflow value.

---

Regardless, this is not the place to be exploring the intricacies of debouncing. As I said I'd recommend doing your own research and, if you need to, seeking help elsewhere.

**Comment by BenjaminVanRyseghem** [comment]
Thanks for your input :smile:

**Pull request closed without merging**
